/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "BootNotificationReqJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static struct BootNotificationReq * cJSON_GetBootNotificationReqValue(const cJSON * j);
static cJSON * cJSON_CreateBootNotificationReq(const struct BootNotificationReq * x);
static void cJSON_DeleteBootNotificationReq(struct BootNotificationReq * x);

struct BootNotificationReq * cJSON_ParseBootNotificationReq(const char * s) {
    struct BootNotificationReq * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetBootNotificationReqValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct BootNotificationReq * cJSON_GetBootNotificationReqValue(const cJSON * j) {
    struct BootNotificationReq * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct BootNotificationReq)))) {
            memset(x, 0, sizeof(struct BootNotificationReq));
            if (cJSON_HasObjectItem(j, "chargeBoxSerialNumber")) {
                x->charge_box_serial_number = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "chargeBoxSerialNumber")));
            }
            if (cJSON_HasObjectItem(j, "chargePointModel")) {
                x->charge_point_model = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "chargePointModel")));
            }
            else {
                if (NULL != (x->charge_point_model = cJSON_malloc(sizeof(char)))) {
                    x->charge_point_model[0] = '\0';
                }
            }
            if (cJSON_HasObjectItem(j, "chargePointSerialNumber")) {
                x->charge_point_serial_number = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "chargePointSerialNumber")));
            }
            if (cJSON_HasObjectItem(j, "chargePointVendor")) {
                x->charge_point_vendor = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "chargePointVendor")));
            }
            else {
                if (NULL != (x->charge_point_vendor = cJSON_malloc(sizeof(char)))) {
                    x->charge_point_vendor[0] = '\0';
                }
            }
            if (cJSON_HasObjectItem(j, "firmwareVersion")) {
                x->firmware_version = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "firmwareVersion")));
            }
            if (cJSON_HasObjectItem(j, "iccid")) {
                x->iccid = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "iccid")));
            }
            if (cJSON_HasObjectItem(j, "imsi")) {
                x->imsi = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "imsi")));
            }
            if (cJSON_HasObjectItem(j, "meterSerialNumber")) {
                x->meter_serial_number = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "meterSerialNumber")));
            }
            if (cJSON_HasObjectItem(j, "meterType")) {
                x->meter_type = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "meterType")));
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateBootNotificationReq(const struct BootNotificationReq * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->charge_box_serial_number) {
                cJSON_AddStringToObject(j, "chargeBoxSerialNumber", x->charge_box_serial_number);
            }
            if (NULL != x->charge_point_model) {
                cJSON_AddStringToObject(j, "chargePointModel", x->charge_point_model);
            }
            else {
                cJSON_AddStringToObject(j, "chargePointModel", "");
            }
            if (NULL != x->charge_point_serial_number) {
                cJSON_AddStringToObject(j, "chargePointSerialNumber", x->charge_point_serial_number);
            }
            if (NULL != x->charge_point_vendor) {
                cJSON_AddStringToObject(j, "chargePointVendor", x->charge_point_vendor);
            }
            else {
                cJSON_AddStringToObject(j, "chargePointVendor", "");
            }
            if (NULL != x->firmware_version) {
                cJSON_AddStringToObject(j, "firmwareVersion", x->firmware_version);
            }
            if (NULL != x->iccid) {
                cJSON_AddStringToObject(j, "iccid", x->iccid);
            }
            if (NULL != x->imsi) {
                cJSON_AddStringToObject(j, "imsi", x->imsi);
            }
            if (NULL != x->meter_serial_number) {
                cJSON_AddStringToObject(j, "meterSerialNumber", x->meter_serial_number);
            }
            if (NULL != x->meter_type) {
                cJSON_AddStringToObject(j, "meterType", x->meter_type);
            }
        }
    }
    return j;
}

char * cJSON_PrintBootNotificationReq(const struct BootNotificationReq * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateBootNotificationReq(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteBootNotificationReq(struct BootNotificationReq * x) {
    if (NULL != x) {
        if (NULL != x->charge_box_serial_number) {
            cJSON_free(x->charge_box_serial_number);
        }
        if (NULL != x->charge_point_model) {
            cJSON_free(x->charge_point_model);
        }
        if (NULL != x->charge_point_serial_number) {
            cJSON_free(x->charge_point_serial_number);
        }
        if (NULL != x->charge_point_vendor) {
            cJSON_free(x->charge_point_vendor);
        }
        if (NULL != x->firmware_version) {
            cJSON_free(x->firmware_version);
        }
        if (NULL != x->iccid) {
            cJSON_free(x->iccid);
        }
        if (NULL != x->imsi) {
            cJSON_free(x->imsi);
        }
        if (NULL != x->meter_serial_number) {
            cJSON_free(x->meter_serial_number);
        }
        if (NULL != x->meter_type) {
            cJSON_free(x->meter_type);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
