/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "BootNotificationConfJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static enum Status_Boot cJSON_GetStatusValue(const cJSON * j);
static cJSON * cJSON_CreateStatus(const enum Status_Boot x);

static struct BootNotificationConf * cJSON_GetBootNotificationConfValue(const cJSON * j);
static cJSON * cJSON_CreateBootNotificationConf(const struct BootNotificationConf * x);
static void cJSON_DeleteBootNotificationConf(struct BootNotificationConf * x);

static enum Status_Boot cJSON_GetStatusValue(const cJSON * j) {
    enum Status_Boot x = 0;
    if (NULL != j) {
        if (!strcmp(cJSON_GetStringValue(j), "Accepted")) x = STATUS_BOOT_ACCEPTED;
        else if (!strcmp(cJSON_GetStringValue(j), "Pending")) x = STATUS_BOOT_PENDING;
        else if (!strcmp(cJSON_GetStringValue(j), "Rejected")) x = STATUS_BOOT_REJECTED;
    }
    return x;
}

static cJSON * cJSON_CreateStatus(const enum Status_Boot x) {
    cJSON * j = NULL;
    switch (x) {
        case STATUS_BOOT_ACCEPTED: j = cJSON_CreateString("Accepted"); break;
        case STATUS_BOOT_PENDING: j = cJSON_CreateString("Pending"); break;
        case STATUS_BOOT_REJECTED: j = cJSON_CreateString("Rejected"); break;
    }
    return j;
}

struct BootNotificationConf * cJSON_ParseBootNotificationConf(const char * s) {
    struct BootNotificationConf * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetBootNotificationConfValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct BootNotificationConf * cJSON_GetBootNotificationConfValue(const cJSON * j) {
    struct BootNotificationConf * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct BootNotificationConf)))) {
            memset(x, 0, sizeof(struct BootNotificationConf));
            if (cJSON_HasObjectItem(j, "currentTime")) {
                x->current_time = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "currentTime")));
            }
            else {
                if (NULL != (x->current_time = cJSON_malloc(sizeof(char)))) {
                    x->current_time[0] = '\0';
                }
            }
            if (cJSON_HasObjectItem(j, "interval")) {
                x->interval = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "interval"));
            }
            if (cJSON_HasObjectItem(j, "status")) {
                x->status = cJSON_GetStatusValue(cJSON_GetObjectItemCaseSensitive(j, "status"));
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateBootNotificationConf(const struct BootNotificationConf * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->current_time) {
                cJSON_AddStringToObject(j, "currentTime", x->current_time);
            }
            else {
                cJSON_AddStringToObject(j, "currentTime", "");
            }
            cJSON_AddNumberToObject(j, "interval", x->interval);
            cJSON_AddItemToObject(j, "status", cJSON_CreateStatus(x->status));
        }
    }
    return j;
}

char * cJSON_PrintBootNotificationConf(const struct BootNotificationConf * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateBootNotificationConf(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteBootNotificationConf(struct BootNotificationConf * x) {
    if (NULL != x) {
        if (NULL != x->current_time) {
            cJSON_free(x->current_time);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
