/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "ClearCacheConfJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static enum Status_Cache cJSON_GetStatusValue(const cJSON * j);
static cJSON * cJSON_CreateStatus(const enum Status_Cache x);

static struct ClearCacheConf * cJSON_GetClearCacheConfValue(const cJSON * j);
static cJSON * cJSON_CreateClearCacheConf(const struct ClearCacheConf * x);
static void cJSON_DeleteClearCacheConf(struct ClearCacheConf * x);

// Modificació: afegeixo l'else de x = -1 i x = -2 i if (cJSON_GetStringValue(j) != NULL) {
static enum Status_Cache cJSON_GetStatusValue(const cJSON * j) {
    enum Status_Cache x = 0;
    if (NULL != j) {
        if (cJSON_GetStringValue(j) != NULL) {
            if (!strcmp(cJSON_GetStringValue(j), "Accepted")) x = STATUS_CACHE_ACCEPTED;
            else if (!strcmp(cJSON_GetStringValue(j), "Rejected")) x = STATUS_CACHE_REJECTED;
            else
                x = -1;
        }
        else
            x = -2;
    }
    return x;
}

static cJSON * cJSON_CreateStatus(const enum Status_Cache x) {
    cJSON * j = NULL;
    switch (x) {
        case STATUS_CACHE_ACCEPTED: j = cJSON_CreateString("Accepted"); break;
        case STATUS_CACHE_REJECTED: j = cJSON_CreateString("Rejected"); break;
    }
    return j;
}

struct ClearCacheConf * cJSON_ParseClearCacheConf(const char * s) {
    struct ClearCacheConf * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetClearCacheConfValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

// Modificació: afegeixo else x->status = -1;
static struct ClearCacheConf * cJSON_GetClearCacheConfValue(const cJSON * j) {
    struct ClearCacheConf * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct ClearCacheConf)))) {
            memset(x, 0, sizeof(struct ClearCacheConf));
            if (cJSON_HasObjectItem(j, "status")) {
                x->status = cJSON_GetStatusValue(cJSON_GetObjectItemCaseSensitive(j, "status"));
            }
            else
                x->status = -1;
        }
    }
    return x;
}

static cJSON * cJSON_CreateClearCacheConf(const struct ClearCacheConf * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddItemToObject(j, "status", cJSON_CreateStatus(x->status));
        }
    }
    return j;
}

char * cJSON_PrintClearCacheConf(const struct ClearCacheConf * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateClearCacheConf(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteClearCacheConf(struct ClearCacheConf * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
