/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "DataTransferReqJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static struct DataTransferReq * cJSON_GetDataTransferReqValue(const cJSON * j);
static cJSON * cJSON_CreateDataTransferReq(const struct DataTransferReq * x);
static void cJSON_DeleteDataTransferReq(struct DataTransferReq * x);

struct DataTransferReq * cJSON_ParseDataTransferReq(const char * s) {
    struct DataTransferReq * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetDataTransferReqValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct DataTransferReq * cJSON_GetDataTransferReqValue(const cJSON * j) {
    struct DataTransferReq * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct DataTransferReq)))) {
            memset(x, 0, sizeof(struct DataTransferReq));
            if (cJSON_HasObjectItem(j, "data")) {
                x->data = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "data")));
            }
            if (cJSON_HasObjectItem(j, "messageId")) {
                x->message_id = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "messageId")));
            }
            if (cJSON_HasObjectItem(j, "vendorId")) {
                x->vendor_id = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "vendorId")));
            }
            else {
                if (NULL != (x->vendor_id = cJSON_malloc(sizeof(char)))) {
                    x->vendor_id[0] = '\0';
                }
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateDataTransferReq(const struct DataTransferReq * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->data) {
                cJSON_AddStringToObject(j, "data", x->data);
            }
            if (NULL != x->message_id) {
                cJSON_AddStringToObject(j, "messageId", x->message_id);
            }
            if (NULL != x->vendor_id) {
                cJSON_AddStringToObject(j, "vendorId", x->vendor_id);
            }
            else {
                cJSON_AddStringToObject(j, "vendorId", "");
            }
        }
    }
    return j;
}

char * cJSON_PrintDataTransferReq(const struct DataTransferReq * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateDataTransferReq(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteDataTransferReq(struct DataTransferReq * x) {
    if (NULL != x) {
        if (NULL != x->data) {
            cJSON_free(x->data);
        }
        if (NULL != x->message_id) {
            cJSON_free(x->message_id);
        }
        if (NULL != x->vendor_id) {
            cJSON_free(x->vendor_id);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
