/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "GetConfigurationReqJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static struct GetConfigurationReq * cJSON_GetGetConfigurationReqValue(const cJSON * j);
static cJSON * cJSON_CreateGetConfigurationReq(const struct GetConfigurationReq * x);
static void cJSON_DeleteGetConfigurationReq(struct GetConfigurationReq * x);

struct GetConfigurationReq * cJSON_ParseGetConfigurationReq(const char * s) {
    struct GetConfigurationReq * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetGetConfigurationReqValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct GetConfigurationReq * cJSON_GetGetConfigurationReqValue(const cJSON * j) {
    struct GetConfigurationReq * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct GetConfigurationReq)))) {
            memset(x, 0, sizeof(struct GetConfigurationReq));
            if (cJSON_HasObjectItem(j, "key")) {
                list_t * x1 = list_create(false, NULL);
                if (NULL != x1) {
                    cJSON * e1 = NULL;
                    cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "key");
                    cJSON_ArrayForEach(e1, j1) {
                        list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
                    }
                    x->key = x1;
                }
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateGetConfigurationReq(const struct GetConfigurationReq * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->key) {
                cJSON * j1 = cJSON_AddArrayToObject(j, "key");
                if (NULL != j1) {
                    char * x1 = list_get_head(x->key);
                    while (NULL != x1) {
                        cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
                        x1 = list_get_next(x->key);
                    }
                }
            }
        }
    }
    return j;
}

char * cJSON_PrintGetConfigurationReq(const struct GetConfigurationReq * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateGetConfigurationReq(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteGetConfigurationReq(struct GetConfigurationReq * x) {
    if (NULL != x) {
        if (NULL != x->key) {
            char * x1 = list_get_head(x->key);
            while (NULL != x1) {
                cJSON_free(x1);
                x1 = list_get_next(x->key);
            }
            list_release(x->key);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
