/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include <stdio.h>
#include "GetConfigurationConfJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static struct ConfigurationKey * cJSON_GetConfigurationKeyValue(const cJSON * j);
static cJSON * cJSON_CreateConfigurationKey(const struct ConfigurationKey * x);
static void cJSON_DeleteConfigurationKey(struct ConfigurationKey * x);

static struct GetConfigurationConf * cJSON_GetGetConfigurationConfValue(const cJSON * j);
static cJSON * cJSON_CreateGetConfigurationConf(const struct GetConfigurationConf * x);
static void cJSON_DeleteGetConfigurationConf(struct GetConfigurationConf * x);

struct ConfigurationKey * cJSON_ParseConfigurationKey(const char * s) {
    struct ConfigurationKey * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetConfigurationKeyValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct ConfigurationKey * cJSON_GetConfigurationKeyValue(const cJSON * j) {
    struct ConfigurationKey * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct ConfigurationKey)))) {
            memset(x, 0, sizeof(struct ConfigurationKey));
            if (cJSON_HasObjectItem(j, "key")) {
                x->key = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "key")));
            }
            else {
                if (NULL != (x->key = cJSON_malloc(sizeof(char)))) {
                    x->key[0] = '\0';
                }
            }
            if (cJSON_HasObjectItem(j, "readonly")) {
                x->readonly = cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(j, "readonly"));
            }
            //else
            //    x->readonly = -1;
            if (cJSON_HasObjectItem(j, "value")) {
                x->value = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "value")));
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateConfigurationKey(const struct ConfigurationKey * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->key) {
                cJSON_AddStringToObject(j, "key", x->key);
            }
            else {
                cJSON_AddStringToObject(j, "key", "");
            }
            cJSON_AddBoolToObject(j, "readonly", x->readonly);
            if (NULL != x->value) {
                cJSON_AddStringToObject(j, "value", x->value);
            }
        }
    }
    return j;
}

char * cJSON_PrintConfigurationKey(const struct ConfigurationKey * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateConfigurationKey(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteConfigurationKey(struct ConfigurationKey * x) {
    if (NULL != x) {
        if (NULL != x->key) {
            cJSON_free(x->key);
        }
        if (NULL != x->value) {
            cJSON_free(x->value);
        }
        cJSON_free(x);
    }
}

struct GetConfigurationConf * cJSON_ParseGetConfigurationConf(const char * s) {
    struct GetConfigurationConf * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetGetConfigurationConfValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct GetConfigurationConf * cJSON_GetGetConfigurationConfValue(const cJSON * j) {
    struct GetConfigurationConf * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct GetConfigurationConf)))) {
            memset(x, 0, sizeof(struct GetConfigurationConf));
            if (cJSON_HasObjectItem(j, "configurationKey")) {
                list_t * x1 = list_create(false, NULL);
                if (NULL != x1) {
                    cJSON * e1 = NULL;
                    cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "configurationKey");
                    cJSON_ArrayForEach(e1, j1) {
                        list_add_tail(x1, cJSON_GetConfigurationKeyValue(e1), sizeof(struct ConfigurationKey *));
                    }
                    x->configuration_key = x1;
                }
            }
            if (cJSON_HasObjectItem(j, "unknownKey")) {
                list_t * x1 = list_create(false, NULL);
                if (NULL != x1) {
                    cJSON * e1 = NULL;
                    cJSON * j1 = cJSON_GetObjectItemCaseSensitive(j, "unknownKey");
                    cJSON_ArrayForEach(e1, j1) {
                        if (cJSON_GetStringValue(e1))
                            list_add_tail(x1, strdup(cJSON_GetStringValue(e1)), sizeof(char *));
                    }
                    x->unknown_key = x1;
                }
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateGetConfigurationConf(const struct GetConfigurationConf * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->configuration_key) {
                cJSON * j1 = cJSON_AddArrayToObject(j, "configurationKey");
                if (NULL != j1) {
                    struct ConfigurationKey * x1 = list_get_head(x->configuration_key);
                    while (NULL != x1) {
                        cJSON_AddItemToArray(j1, cJSON_CreateConfigurationKey(x1));
                        x1 = list_get_next(x->configuration_key);
                    }
                }
            }
            if (NULL != x->unknown_key) {
                cJSON * j1 = cJSON_AddArrayToObject(j, "unknownKey");
                if (NULL != j1) {
                    char * x1 = list_get_head(x->unknown_key);
                    while (NULL != x1) {
                        cJSON_AddItemToArray(j1, cJSON_CreateString(x1));
                        x1 = list_get_next(x->unknown_key);
                    }
                }
            }
        }
    }
    return j;
}

char * cJSON_PrintGetConfigurationConf(const struct GetConfigurationConf * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateGetConfigurationConf(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteGetConfigurationConf(struct GetConfigurationConf * x) {
    if (NULL != x) {
        if (NULL != x->configuration_key) {
            struct ConfigurationKey * x1 = list_get_head(x->configuration_key);
            while (NULL != x1) {
                cJSON_DeleteConfigurationKey(x1);
                x1 = list_get_next(x->configuration_key);
            }
            list_release(x->configuration_key);
        }
        if (NULL != x->unknown_key) {
            char * x1 = list_get_head(x->unknown_key);
            while (NULL != x1) {
                cJSON_free(x1);
                x1 = list_get_next(x->unknown_key);
            }
            list_release(x->unknown_key);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
