/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "ResetReqJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static enum Type_Reset cJSON_GetTypeValue(const cJSON * j);
static cJSON * cJSON_CreateType(const enum Type_Reset x);

static struct ResetReq * cJSON_GetResetReqValue(const cJSON * j);
static cJSON * cJSON_CreateResetReq(const struct ResetReq * x);
static void cJSON_DeleteResetReq(struct ResetReq * x);

static enum Type_Reset cJSON_GetTypeValue(const cJSON * j) {
    enum Type_Reset x = 0;
    if (NULL != j) {
        if (!strcmp(cJSON_GetStringValue(j), "Hard")) x = TYPE_HARD;
        else if (!strcmp(cJSON_GetStringValue(j), "Soft")) x = TYPE_SOFT;
    }
    return x;
}

static cJSON * cJSON_CreateType(const enum Type_Reset x) {
    cJSON * j = NULL;
    switch (x) {
        case TYPE_HARD: j = cJSON_CreateString("Hard"); break;
        case TYPE_SOFT: j = cJSON_CreateString("Soft"); break;
    }
    return j;
}

struct ResetReq * cJSON_ParseResetReq(const char * s) {
    struct ResetReq * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetResetReqValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

// Modificació: x->type = -1
static struct ResetReq * cJSON_GetResetReqValue(const cJSON * j) {
    struct ResetReq * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct ResetReq)))) {
            memset(x, 0, sizeof(struct ResetReq));
            if (cJSON_HasObjectItem(j, "type")) {
                x->type = cJSON_GetTypeValue(cJSON_GetObjectItemCaseSensitive(j, "type"));
            }
            else
                x->type = -1;
        }
    }
    return x;
}

static cJSON * cJSON_CreateResetReq(const struct ResetReq * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddItemToObject(j, "type", cJSON_CreateType(x->type));
        }
    }
    return j;
}

char * cJSON_PrintResetReq(const struct ResetReq * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateResetReq(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteResetReq(struct ResetReq * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
