/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "StartTransactionConfJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static enum Status_Start cJSON_GetStatusValue(const cJSON * j);
static cJSON * cJSON_CreateStatus(const enum Status_Start x);

static struct IdTagInfo_Start * cJSON_GetIdTagInfoValue(const cJSON * j);
static cJSON * cJSON_CreateIdTagInfo(const struct IdTagInfo_Start * x);
static void cJSON_DeleteIdTagInfo(struct IdTagInfo_Start * x);

static struct StartTransactionConf * cJSON_GetStartTransactionConfValue(const cJSON * j);
static cJSON * cJSON_CreateStartTransactionConf(const struct StartTransactionConf * x);
static void cJSON_DeleteStartTransactionConf(struct StartTransactionConf * x);

static enum Status_Start cJSON_GetStatusValue(const cJSON * j) {
    enum Status_Start x = 0;
    if (NULL != j) {
        if (!strcmp(cJSON_GetStringValue(j), "Accepted")) x = STATUS_START_ACCEPTED;
        else if (!strcmp(cJSON_GetStringValue(j), "Blocked")) x = STATUS_START_BLOCKED;
        else if (!strcmp(cJSON_GetStringValue(j), "ConcurrentTx")) x = STATUS_START_CONCURRENT_TX;
        else if (!strcmp(cJSON_GetStringValue(j), "Expired")) x = STATUS_START_EXPIRED;
        else if (!strcmp(cJSON_GetStringValue(j), "Invalid")) x = STATUS_START_INVALID;
    }
    return x;
}

static cJSON * cJSON_CreateStatus(const enum Status_Start x) {
    cJSON * j = NULL;
    switch (x) {
        case STATUS_START_ACCEPTED: j = cJSON_CreateString("Accepted"); break;
        case STATUS_START_BLOCKED: j = cJSON_CreateString("Blocked"); break;
        case STATUS_START_CONCURRENT_TX: j = cJSON_CreateString("ConcurrentTx"); break;
        case STATUS_START_EXPIRED: j = cJSON_CreateString("Expired"); break;
        case STATUS_START_INVALID: j = cJSON_CreateString("Invalid"); break;
    }
    return j;
}

struct IdTagInfo_Start * cJSON_ParseIdTagInfoStart(const char * s) {
    struct IdTagInfo_Start * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetIdTagInfoValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct IdTagInfo_Start * cJSON_GetIdTagInfoValue(const cJSON * j) {
    struct IdTagInfo_Start * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct IdTagInfo_Start)))) {
            memset(x, 0, sizeof(struct IdTagInfo_Start));
            if (cJSON_HasObjectItem(j, "expiryDate")) {
                x->expiry_date = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "expiryDate")));
            }
            if (cJSON_HasObjectItem(j, "parentIdTag")) {
                x->parent_id_tag = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "parentIdTag")));
            }
            if (cJSON_HasObjectItem(j, "status")) {
                x->status = cJSON_GetStatusValue(cJSON_GetObjectItemCaseSensitive(j, "status"));
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateIdTagInfo(const struct IdTagInfo_Start * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->expiry_date) {
                cJSON_AddStringToObject(j, "expiryDate", x->expiry_date);
            }
            if (NULL != x->parent_id_tag) {
                cJSON_AddStringToObject(j, "parentIdTag", x->parent_id_tag);
            }
            cJSON_AddItemToObject(j, "status", cJSON_CreateStatus(x->status));
        }
    }
    return j;
}

char * cJSON_PrintIdTagInfo(const struct IdTagInfo_Start * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateIdTagInfo(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteIdTagInfo(struct IdTagInfo_Start * x) {
    if (NULL != x) {
        if (NULL != x->expiry_date) {
            cJSON_free(x->expiry_date);
        }
        if (NULL != x->parent_id_tag) {
            cJSON_free(x->parent_id_tag);
        }
        cJSON_free(x);
    }
}

struct StartTransactionConf * cJSON_ParseStartTransactionConf(const char * s) {
    struct StartTransactionConf * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetStartTransactionConfValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct StartTransactionConf * cJSON_GetStartTransactionConfValue(const cJSON * j) {
    struct StartTransactionConf * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct StartTransactionConf)))) {
            memset(x, 0, sizeof(struct StartTransactionConf));
            if (cJSON_HasObjectItem(j, "idTagInfo")) {
                x->id_tag_info = cJSON_GetIdTagInfoValue(cJSON_GetObjectItemCaseSensitive(j, "idTagInfo"));
            }
            if (cJSON_HasObjectItem(j, "transactionId")) {
                x->transaction_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "transactionId"));
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateStartTransactionConf(const struct StartTransactionConf * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddItemToObject(j, "idTagInfo", cJSON_CreateIdTagInfo(x->id_tag_info));
            cJSON_AddNumberToObject(j, "transactionId", x->transaction_id);
        }
    }
    return j;
}

char * cJSON_PrintStartTransactionConf(const struct StartTransactionConf * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateStartTransactionConf(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteStartTransactionConf(struct StartTransactionConf * x) {
    if (NULL != x) {
        if (NULL != x->id_tag_info) {
            cJSON_DeleteIdTagInfo(x->id_tag_info);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
