/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "StartTransactionReqJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static struct StartTransactionReq * cJSON_GetStartTransactionReqValue(const cJSON * j);
static cJSON * cJSON_CreateStartTransactionReq(const struct StartTransactionReq * x);
static void cJSON_DeleteStartTransactionReq(struct StartTransactionReq * x);

struct StartTransactionReq * cJSON_ParseStartTransactionReq(const char * s) {
    struct StartTransactionReq * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetStartTransactionReqValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

// Modificació: afegits els else de connector_id = -1 i meterStart = -1 quan no existeixen, i també l'else de reservationId
static struct StartTransactionReq * cJSON_GetStartTransactionReqValue(const cJSON * j) {
    struct StartTransactionReq * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct StartTransactionReq)))) {
            memset(x, 0, sizeof(struct StartTransactionReq));
            if (cJSON_HasObjectItem(j, "connectorId")) {
                x->connector_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "connectorId"));
            }
            else
                x->connector_id = -1;
            if (cJSON_HasObjectItem(j, "idTag")) {
                x->id_tag = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "idTag")));
            }
            else {
                if (NULL != (x->id_tag = cJSON_malloc(sizeof(char)))) {
                    x->id_tag[0] = '\0';
                }
            }
            if (cJSON_HasObjectItem(j, "meterStart")) {
                x->meter_start = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "meterStart"));
            }
            else
                x->meter_start = -1;
            if (cJSON_HasObjectItem(j, "reservationId")) {
                if (NULL != (x->reservation_id = cJSON_malloc(sizeof(int64_t)))) {
                    if (cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "reservationId")) > 0) {
                        *x->reservation_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "reservationId"));
                    }
                    else {
                        *x->reservation_id = -1;
                    }
                }
            }
            if (cJSON_HasObjectItem(j, "timestamp")) {
                x->timestamp = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "timestamp")));
            }
            else {
                if (NULL != (x->timestamp = cJSON_malloc(sizeof(char)))) {
                    x->timestamp[0] = '\0';
                }
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateStartTransactionReq(const struct StartTransactionReq * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddNumberToObject(j, "connectorId", x->connector_id);
            if (NULL != x->id_tag) {
                cJSON_AddStringToObject(j, "idTag", x->id_tag);
            }
            else {
                cJSON_AddStringToObject(j, "idTag", "");
            }
            cJSON_AddNumberToObject(j, "meterStart", x->meter_start);
            if (NULL != x->reservation_id) {
                cJSON_AddNumberToObject(j, "reservationId", *x->reservation_id);
            }
            if (NULL != x->timestamp) {
                cJSON_AddStringToObject(j, "timestamp", x->timestamp);
            }
            else {
                cJSON_AddStringToObject(j, "timestamp", "");
            }
        }
    }
    return j;
}

char * cJSON_PrintStartTransactionReq(const struct StartTransactionReq * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateStartTransactionReq(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteStartTransactionReq(struct StartTransactionReq * x) {
    if (NULL != x) {
        if (NULL != x->id_tag) {
            cJSON_free(x->id_tag);
        }
        if (NULL != x->reservation_id) {
            cJSON_free(x->reservation_id);
        }
        if (NULL != x->timestamp) {
            cJSON_free(x->timestamp);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
