/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "StatusNotificationReqJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static enum ErrorCode cJSON_GetErrorCodeValue(const cJSON * j);
static cJSON * cJSON_CreateErrorCode(const enum ErrorCode x);

static enum Status_Status cJSON_GetStatusValue(const cJSON * j);
static cJSON * cJSON_CreateStatus(const enum Status_Status x);

static struct StatusNotificationReq * cJSON_GetStatusNotificationReqValue(const cJSON * j);
static cJSON * cJSON_CreateStatusNotificationReq(const struct StatusNotificationReq * x);
static void cJSON_DeleteStatusNotificationReq(struct StatusNotificationReq * x);

// Modificació: afegeixo l'else de x = -1 i x = -2
static enum ErrorCode cJSON_GetErrorCodeValue(const cJSON * j) {
    enum ErrorCode x = 0;
    if (NULL != j) {
        if (cJSON_GetStringValue(j) != NULL) {
            if (!strcmp(cJSON_GetStringValue(j), "ConnectorLockFailure")) x = ERRORCODE_CONNECTOR_LOCK_FAILURE;
            else if (!strcmp(cJSON_GetStringValue(j), "EVCommunicationError")) x = ERRORCODE_EV_COMMUNICATION_ERROR;
            else if (!strcmp(cJSON_GetStringValue(j), "GroundFailure")) x = ERRORCODE_GROUND_FAILURE;
            else if (!strcmp(cJSON_GetStringValue(j), "HighTemperature")) x = ERRORCODE_HIGH_TEMPERATURE;
            else if (!strcmp(cJSON_GetStringValue(j), "InternalError")) x = ERRORCODE_INTERNAL_ERROR;
            else if (!strcmp(cJSON_GetStringValue(j), "LocalListConflict")) x = ERRORCODE_LOCAL_LIST_CONFLICT;
            else if (!strcmp(cJSON_GetStringValue(j), "NoError")) x = ERRORCODE_NO_ERROR;
            else if (!strcmp(cJSON_GetStringValue(j), "OtherError")) x = ERRORCODE_OTHER_ERROR;
            else if (!strcmp(cJSON_GetStringValue(j), "OverCurrentFailure")) x = ERRORCODE_OVER_CURRENT_FAILURE;
            else if (!strcmp(cJSON_GetStringValue(j), "OverVoltage")) x = ERRORCODE_OVER_VOLTAGE;
            else if (!strcmp(cJSON_GetStringValue(j), "PowerMeterFailure")) x = ERRORCODE_POWER_METER_FAILURE;
            else if (!strcmp(cJSON_GetStringValue(j), "PowerSwitchFailure")) x = ERRORCODE_POWER_SWITCH_FAILURE;
            else if (!strcmp(cJSON_GetStringValue(j), "ReaderFailure")) x = ERRORCODE_READER_FAILURE;
            else if (!strcmp(cJSON_GetStringValue(j), "ResetFailure")) x = ERRORCODE_RESET_FAILURE;
            else if (!strcmp(cJSON_GetStringValue(j), "UnderVoltage")) x = ERRORCODE_UNDER_VOLTAGE;
            else if (!strcmp(cJSON_GetStringValue(j), "WeakSignal")) x = ERRORCODE_WEAK_SIGNAL;
            else
                x = -1;
        }
        else
            x = -2;
    }
    return x;
}

static cJSON * cJSON_CreateErrorCode(const enum ErrorCode x) {
    cJSON * j = NULL;
    switch (x) {
        case ERRORCODE_CONNECTOR_LOCK_FAILURE: j = cJSON_CreateString("ConnectorLockFailure"); break;
        case ERRORCODE_EV_COMMUNICATION_ERROR: j = cJSON_CreateString("EVCommunicationError"); break;
        case ERRORCODE_GROUND_FAILURE: j = cJSON_CreateString("GroundFailure"); break;
        case ERRORCODE_HIGH_TEMPERATURE: j = cJSON_CreateString("HighTemperature"); break;
        case ERRORCODE_INTERNAL_ERROR: j = cJSON_CreateString("InternalError"); break;
        case ERRORCODE_LOCAL_LIST_CONFLICT: j = cJSON_CreateString("LocalListConflict"); break;
        case ERRORCODE_NO_ERROR: j = cJSON_CreateString("NoError"); break;
        case ERRORCODE_OTHER_ERROR: j = cJSON_CreateString("OtherError"); break;
        case ERRORCODE_OVER_CURRENT_FAILURE: j = cJSON_CreateString("OverCurrentFailure"); break;
        case ERRORCODE_OVER_VOLTAGE: j = cJSON_CreateString("OverVoltage"); break;
        case ERRORCODE_POWER_METER_FAILURE: j = cJSON_CreateString("PowerMeterFailure"); break;
        case ERRORCODE_POWER_SWITCH_FAILURE: j = cJSON_CreateString("PowerSwitchFailure"); break;
        case ERRORCODE_READER_FAILURE: j = cJSON_CreateString("ReaderFailure"); break;
        case ERRORCODE_RESET_FAILURE: j = cJSON_CreateString("ResetFailure"); break;
        case ERRORCODE_UNDER_VOLTAGE: j = cJSON_CreateString("UnderVoltage"); break;
        case ERRORCODE_WEAK_SIGNAL: j = cJSON_CreateString("WeakSignal"); break;
    }
    return j;
}

// Modificació: afegeixo l'else de x = -1 i x = -2
static enum Status_Status cJSON_GetStatusValue(const cJSON * j) {
    enum Status_Status x = 0;
    if (NULL != j) {
        if (cJSON_GetStringValue(j) != NULL) {
            if (!strcmp(cJSON_GetStringValue(j), "Available")) x = STATUS_STATUS_AVAILABLE;
            else if (!strcmp(cJSON_GetStringValue(j), "Charging")) x = STATUS_STATUS_CHARGING;
            else if (!strcmp(cJSON_GetStringValue(j), "Faulted")) x = STATUS_STATUS_FAULTED;
            else if (!strcmp(cJSON_GetStringValue(j), "Finishing")) x = STATUS_STATUS_FINISHING;
            else if (!strcmp(cJSON_GetStringValue(j), "Preparing")) x = STATUS_STATUS_PREPARING;
            else if (!strcmp(cJSON_GetStringValue(j), "Reserved")) x = STATUS_STATUS_RESERVED;
            else if (!strcmp(cJSON_GetStringValue(j), "SuspendedEV")) x = STATUS_STATUS_SUSPENDED_EV;
            else if (!strcmp(cJSON_GetStringValue(j), "SuspendedEVSE")) x = STATUS_STATUS_SUSPENDED_EVSE;
            else if (!strcmp(cJSON_GetStringValue(j), "Unavailable")) x = STATUS_STATUS_UNAVAILABLE;
            else
                x = -1;
        }
        else
            x = -2;
    }
    return x;
}

static cJSON * cJSON_CreateStatus(const enum Status_Status x) {
    cJSON * j = NULL;
    switch (x) {
        case STATUS_STATUS_AVAILABLE: j = cJSON_CreateString("Available"); break;
        case STATUS_STATUS_CHARGING: j = cJSON_CreateString("Charging"); break;
        case STATUS_STATUS_FAULTED: j = cJSON_CreateString("Faulted"); break;
        case STATUS_STATUS_FINISHING: j = cJSON_CreateString("Finishing"); break;
        case STATUS_STATUS_PREPARING: j = cJSON_CreateString("Preparing"); break;
        case STATUS_STATUS_RESERVED: j = cJSON_CreateString("Reserved"); break;
        case STATUS_STATUS_SUSPENDED_EV: j = cJSON_CreateString("SuspendedEV"); break;
        case STATUS_STATUS_SUSPENDED_EVSE: j = cJSON_CreateString("SuspendedEVSE"); break;
        case STATUS_STATUS_UNAVAILABLE: j = cJSON_CreateString("Unavailable"); break;
    }
    return j;
}

struct StatusNotificationReq * cJSON_ParseStatusNotificationReq(const char * s) {
    struct StatusNotificationReq * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetStatusNotificationReqValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

// Modificació: afegeixo l'else de connector_id = -1, error_code = -1 i status = -1
static struct StatusNotificationReq * cJSON_GetStatusNotificationReqValue(const cJSON * j) {
    struct StatusNotificationReq * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct StatusNotificationReq)))) {
            memset(x, 0, sizeof(struct StatusNotificationReq));
            if (cJSON_HasObjectItem(j, "connectorId")) {
                x->connector_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "connectorId"));
            }
            else
                x->connector_id = -1;
            if (cJSON_HasObjectItem(j, "errorCode")) {
                x->error_code = cJSON_GetErrorCodeValue(cJSON_GetObjectItemCaseSensitive(j, "errorCode"));
            }
            else
                x->error_code = -1;
            if (cJSON_HasObjectItem(j, "info")) {
                x->info = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "info")));
            }
            if (cJSON_HasObjectItem(j, "status")) {
                x->status = cJSON_GetStatusValue(cJSON_GetObjectItemCaseSensitive(j, "status"));
            }
            else
                x->status = -1;
            if (cJSON_HasObjectItem(j, "timestamp")) {
                x->timestamp = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "timestamp")));
            }
            if (cJSON_HasObjectItem(j, "vendorErrorCode")) {
                x->vendor_error_code = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "vendorErrorCode")));
            }
            if (cJSON_HasObjectItem(j, "vendorId")) {
                x->vendor_id = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "vendorId")));
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateStatusNotificationReq(const struct StatusNotificationReq * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddNumberToObject(j, "connectorId", x->connector_id);
            cJSON_AddItemToObject(j, "errorCode", cJSON_CreateErrorCode(x->error_code));
            if (NULL != x->info) {
                cJSON_AddStringToObject(j, "info", x->info);
            }
            cJSON_AddItemToObject(j, "status", cJSON_CreateStatus(x->status));
            if (NULL != x->timestamp) {
                cJSON_AddStringToObject(j, "timestamp", x->timestamp);
            }
            if (NULL != x->vendor_error_code) {
                cJSON_AddStringToObject(j, "vendorErrorCode", x->vendor_error_code);
            }
            if (NULL != x->vendor_id) {
                cJSON_AddStringToObject(j, "vendorId", x->vendor_id);
            }
        }
    }
    return j;
}

char * cJSON_PrintStatusNotificationReq(const struct StatusNotificationReq * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateStatusNotificationReq(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteStatusNotificationReq(struct StatusNotificationReq * x) {
    if (NULL != x) {
        if (NULL != x->info) {
            cJSON_free(x->info);
        }
        if (NULL != x->timestamp) {
            cJSON_free(x->timestamp);
        }
        if (NULL != x->vendor_error_code) {
            cJSON_free(x->vendor_error_code);
        }
        if (NULL != x->vendor_id) {
            cJSON_free(x->vendor_id);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
