/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "StopTransactionConfJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static enum Status_Stop cJSON_GetStatusValue(const cJSON * j);
static cJSON * cJSON_CreateStatus(const enum Status_Stop x);

static struct IdTagInfo_Stop * cJSON_GetIdTagInfoValue(const cJSON * j);
static cJSON * cJSON_CreateIdTagInfo(const struct IdTagInfo_Stop * x);
static void cJSON_DeleteIdTagInfo(struct IdTagInfo_Stop * x);

static struct StopTransactionConf * cJSON_GetStopTransactionConfValue(const cJSON * j);
static cJSON * cJSON_CreateStopTransactionConf(const struct StopTransactionConf * x);
static void cJSON_DeleteStopTransactionConf(struct StopTransactionConf * x);

static enum Status_Stop cJSON_GetStatusValue(const cJSON * j) {
    enum Status_Stop x = 0;
    if (NULL != j) {
        if (!strcmp(cJSON_GetStringValue(j), "Accepted")) x = STATUS_STOP_ACCEPTED;
        else if (!strcmp(cJSON_GetStringValue(j), "Blocked")) x = STATUS_STOP_BLOCKED;
        else if (!strcmp(cJSON_GetStringValue(j), "ConcurrentTx")) x = STATUS_STOP_CONCURRENT_TX;
        else if (!strcmp(cJSON_GetStringValue(j), "Expired")) x = STATUS_STOP_EXPIRED;
        else if (!strcmp(cJSON_GetStringValue(j), "Invalid")) x = STATUS_STOP_INVALID;
    }
    return x;
}

static cJSON * cJSON_CreateStatus(const enum Status_Stop x) {
    cJSON * j = NULL;
    switch (x) {
        case STATUS_STOP_ACCEPTED: j = cJSON_CreateString("Accepted"); break;
        case STATUS_STOP_BLOCKED: j = cJSON_CreateString("Blocked"); break;
        case STATUS_STOP_CONCURRENT_TX: j = cJSON_CreateString("ConcurrentTx"); break;
        case STATUS_STOP_EXPIRED: j = cJSON_CreateString("Expired"); break;
        case STATUS_STOP_INVALID: j = cJSON_CreateString("Invalid"); break;
    }
    return j;
}

struct IdTagInfo_Stop * cJSON_ParseIdTagInfo(const char * s) {
    struct IdTagInfo_Stop * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetIdTagInfoValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct IdTagInfo_Stop * cJSON_GetIdTagInfoValue(const cJSON * j) {
    struct IdTagInfo_Stop * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct IdTagInfo_Stop)))) {
            memset(x, 0, sizeof(struct IdTagInfo_Stop));
            if (cJSON_HasObjectItem(j, "expiryDate")) {
                x->expiry_date = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "expiryDate")));
            }
            if (cJSON_HasObjectItem(j, "parentIdTag")) {
                x->parent_id_tag = mystrdup(cJSON_GetStringValue(cJSON_GetObjectItemCaseSensitive(j, "parentIdTag")));
            }
            if (cJSON_HasObjectItem(j, "status")) {
                x->status = cJSON_GetStatusValue(cJSON_GetObjectItemCaseSensitive(j, "status"));
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateIdTagInfo(const struct IdTagInfo_Stop * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->expiry_date) {
                cJSON_AddStringToObject(j, "expiryDate", x->expiry_date);
            }
            if (NULL != x->parent_id_tag) {
                cJSON_AddStringToObject(j, "parentIdTag", x->parent_id_tag);
            }
            cJSON_AddItemToObject(j, "status", cJSON_CreateStatus(x->status));
        }
    }
    return j;
}

char * cJSON_PrintIdTagInfo_Stop(const struct IdTagInfo_Stop * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateIdTagInfo(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteIdTagInfo(struct IdTagInfo_Stop * x) {
    if (NULL != x) {
        if (NULL != x->expiry_date) {
            cJSON_free(x->expiry_date);
        }
        if (NULL != x->parent_id_tag) {
            cJSON_free(x->parent_id_tag);
        }
        cJSON_free(x);
    }
}

struct StopTransactionConf * cJSON_ParseStopTransactionConf(const char * s) {
    struct StopTransactionConf * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetStopTransactionConfValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

static struct StopTransactionConf * cJSON_GetStopTransactionConfValue(const cJSON * j) {
    struct StopTransactionConf * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct StopTransactionConf)))) {
            memset(x, 0, sizeof(struct StopTransactionConf));
            if (cJSON_HasObjectItem(j, "idTagInfo")) {
                x->id_tag_info = cJSON_GetIdTagInfoValue(cJSON_GetObjectItemCaseSensitive(j, "idTagInfo"));
            }
        }
    }
    return x;
}

static cJSON * cJSON_CreateStopTransactionConf(const struct StopTransactionConf * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            if (NULL != x->id_tag_info) {
                cJSON_AddItemToObject(j, "idTagInfo", cJSON_CreateIdTagInfo(x->id_tag_info));
            }
        }
    }
    return j;
}

char * cJSON_PrintStopTransactionConf(const struct StopTransactionConf * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateStopTransactionConf(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteStopTransactionConf(struct StopTransactionConf * x) {
    if (NULL != x) {
        if (NULL != x->id_tag_info) {
            cJSON_DeleteIdTagInfo(x->id_tag_info);
        }
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
