/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __STDOUT__
#define __STDOUT__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>
#include <hashtable.h>
#include <list.h>
#include "UnlockConnectorReqJSON.h"
#include "mystrdup.h"

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif
#ifndef cJSON_Map
#define cJSON_Map (1 << 16)
#endif
#ifndef cJSON_Enum
#define cJSON_Enum (1 << 17)
#endif

static struct UnlockConnectorReq * cJSON_GetUnlockConnectorReqValue(const cJSON * j);
static cJSON * cJSON_CreateUnlockConnectorReq(const struct UnlockConnectorReq * x);
static void cJSON_DeleteUnlockConnectorReq(struct UnlockConnectorReq * x);

struct UnlockConnectorReq * cJSON_ParseUnlockConnectorReq(const char * s) {
    struct UnlockConnectorReq * x = NULL;
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            x = cJSON_GetUnlockConnectorReqValue(j);
            cJSON_Delete(j);
        }
    }
    return x;
}

// Modificació: x->connecotr_id = -1
static struct UnlockConnectorReq * cJSON_GetUnlockConnectorReqValue(const cJSON * j) {
    struct UnlockConnectorReq * x = NULL;
    if (NULL != j) {
        if (NULL != (x = cJSON_malloc(sizeof(struct UnlockConnectorReq)))) {
            memset(x, 0, sizeof(struct UnlockConnectorReq));
            if (cJSON_HasObjectItem(j, "connectorId")) {
                x->connector_id = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "connectorId"));
            }
            else
                x->connector_id = -1;
        }
    }
    return x;
}

static cJSON * cJSON_CreateUnlockConnectorReq(const struct UnlockConnectorReq * x) {
    cJSON * j = NULL;
    if (NULL != x) {
        if (NULL != (j = cJSON_CreateObject())) {
            cJSON_AddNumberToObject(j, "connectorId", x->connector_id);
        }
    }
    return j;
}

char * cJSON_PrintUnlockConnectorReq(const struct UnlockConnectorReq * x) {
    char * s = NULL;
    if (NULL != x) {
        cJSON * j = cJSON_CreateUnlockConnectorReq(x);
        if (NULL != j) {
            s = cJSON_Print(j);
            cJSON_Delete(j);
        }
    }
    return s;
}

static void cJSON_DeleteUnlockConnectorReq(struct UnlockConnectorReq * x) {
    if (NULL != x) {
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __STDOUT__ */
